export const anneeData = [
    { value: 'premiere-annee', label: "Première année"},
    { value: 'deuxieme-annee', label: "Deuxième année"},
    { value: 'khube', label: "Khûbe"},
]
export const matiereData = [
    { value: 'maths-appro-HGG', label: "Maths Appro - HGG"},
    { value: 'maths-appli-HGG', label: "Maths Appli - HGG"},
    { value: 'maths-appro-ESH', label: "Maths Appro - ESH"},
    { value: 'maths-appli-ESH', label: "Maths Appli - ESH"},
]
export const prepaData = [
  { value: "saintegenevieve", label: "Sainte-Geneviève" },
  { value: "myprepa", label: "MyPrepa" },
  { value: "madeleinedanielou", label: "Madeleine Daniélou" },
  { value: "louislegrand", label: "Louis Le Grand" },
  { value: "notredamedugrandchamp", label: "Notre-Dame du Grandchamp" },
  { value: "henriiv", label: "Henri IV" },
  { value: "stanislas", label: "Stanislas" },
  { value: "saintemarie", label: "Sainte-Marie" },
  { value: "saintlouisdegonzague", label: "Saint-Louis de Gonzague" },
  { value: "lakanal", label: "Lakanal" },
  { value: "hoche", label: "Hoche" },
  { value: "notredamedesaintecroix", label: "Notre-Dame de Sainte-Croix" },
  { value: "laprepaautrementcoursschloesing", label: "La Prépa Autrement - Cours Schloesing" },
  { value: "saintlouis", label: "Saint-Louis" },
  { value: "jansondesailly", label: "Janson de Sailly" },
  { value: "weid", label: "WeiD" },
  { value: "leparc", label: "Le Parc" },
  { value: "leschartreux", label: "Les Chartreux" },
  { value: "ipesupprepacom", label: "Ipesup - Prépacom" },
  { value: "saintmicheldupicpus", label: "Saint-Michel de Picpus" },
  { value: "ampere", label: "Ampère" },
  { value: "champollion", label: "Champollion" },
  { value: "renecassin", label: "René Cassin" },
  { value: "chateaubriand", label: "Chateaubriand" },
  { value: "pierredeferma", label: "Pierre de Fermat" },
  { value: "lavoisier", label: "Lavoisier" },
  { value: "joffre", label: "Joffre" },
  { value: "michelet", label: "Michelet" },
  { value: "nelsonmandela", label: "Nelson Mandela" },
  { value: "marcelinberthelot", label: "Marcelin Berthelot" },
  { value: "montaigne", label: "Montaigne" },
  { value: "saintjust", label: "Saint-Just" },
  { value: "ozenne", label: "Ozenne" },
  { value: "saintvincentprovidence", label: "Saint-Vincent Providence" },
  { value: "montaigne", label: "Montaigne" },
  { value: "integrale", label: "Intégrale" },
  { value: "kleber", label: "Kléber" },
  { value: "claudebernard", label: "Claude Bernard" },
  { value: "clemenceau", label: "Clemenceau" },
  { value: "labruyere", label: "La Bruyère" },
  { value: "lyceeinternationaldevalbonne", label: "Lycée international de Valbonne" },
  { value: "blaisepascal", label: "Blaise Pascal" },
  { value: "massena", label: "Masséna" },
  { value: "thiers", label: "Thiers" },
  { value: "carnot", label: "Carnot" },
  { value: "claudefauriel", label: "Claude Fauriel" },
  { value: "gabrieltouchardwashington", label: "Gabriel Touchard - Washington" },
  { value: "notredamedelamerci", label: "Notre-Dame de la Merci" },
  { value: "berthollet", label: "Berthollet" },
  { value: "claudemonet", label: "Claude Monet" },
  { value: "gustaveflaubert", label: "Gustave Flaubert" },
  { value: "chavagnes", label: "Chavagnes" },
  { value: "malherbe", label: "Malherbe" },
  { value: "prepacommerciajaformation", label: "Prépa Commercia - JA Formation" },
  { value: "stanislascannes", label: "Stanislas Cannes" },
  { value: "georgesdelatour", label: "Georges de la Tour" },
  { value: "henrimoissan", label: "Henri Moissan" },
  { value: "louisbarthou", label: "Louis Barthou" },
  { value: "paulcezanne", label: "Paul Cézanne" },
  { value: "saintjosephduloquidy", label: "Saint-Joseph du Loquidy" },
  { value: "henripoincare", label: "Henri Poincaré" },
  { value: "lanativite", label: "La Nativité" },
  { value: "saintexupery", label: "Saint-Exupéry" },
  { value: "saintemariegrandlebrun", label: "Sainte-Marie Grand Lebrun" },
  { value: "teilharddechardin", label: "Teilhard de Chardin" },
  { value: "alfredkastler", label: "Alfred Kastler" },
  { value: "chaptal", label: "Chaptal" },
  { value: "mariedechampagne", label: "Marie de Champagne" },
  { value: "saintcharles", label: "Saint-Charles" },
  { value: "saintexuperylarochelle", label: "Saint-Exupéry La Rochelle" },
  { value: "saliege", label: "Saliège" },
  { value: "joachimdubellay", label: "Joachim du Bellay" },
  { value: "carnotdijon", label: "Carnot Dijon" },
  { value: "descartes", label: "Descartes" },
  { value: "jeannedarc", label: "Jeanne d'Arc" },
  { value: "laperousekerichen", label: "La Pérouse - Kerichen" },
  { value: "albertschweitzer", label: "Albert Schweitzer" },
  { value: "alienordaquitaine", label: "Aliénor d'Aquitaine" },
  { value: "edgarquentin", label: "Edgar Quinet" },
  { value: "fabert", label: "Fabert" },
  { value: "faidherbe", label: "Faidherbe" },
  { value: "georgesclemenceau", label: "Georges Clemenceau" },
  { value: "micheldemontaigne", label: "Michel de Montaigne" },
  { value: "lafoliesaintjames", label: "La Folie Saint-James" },
  { value: "pierrecorneille", label: "Pierre Corneille" },
  { value: "jeannedalbret", label: "Jeanne d'Albret" },
  { value: "parcdevilgenis", label: "Parc de Vilgénis" },
  { value: "alexandredumas", label: "Alexandre Dumas" },
  { value: "descartesantony", label: "Descartes Antony" },
  { value: "gaylussac", label: "Gay-Lussac" },
  { value: "heleneboucher", label: "Hélène Boucher" },
  { value: "charlesdegaulle", label: "Charles de Gaulle" },
  { value: "dominiquevillars", label: "Dominique Villars" },
  { value: "ipecomprepa", label: "Ipécom - Prépa Victor Hugo" },
  { value: "jeanbaptistecorot", label: "Jean-Baptiste Corot" },
  { value: "saintbenigne", label: "Saint-Bénigne" },
  { value: "notredamedubonsecours", label: "Notre-Dame de Bon Secours" },
  { value: "saintalyre", label: "Saint-Alyre" },
  { value: "gustavecourbet", label: "Gustave Courbet" },
  { value: "saintcharlessaintecroix", label: "Saint-Charles Sainte-Croix" },
  { value: "saintexuperymanteslajolie", label: "Saint-Exupéry Mantes-la-Jolie" },
  { value: "emmanueldalzon", label: "Emmanuel d'Alzon" },
  { value: "lacadenelle", label: "La Cadenelle" },
  { value: "jeanxxiii", label: "Jean XXIII" },
  { value: "baimbridge", label: "Baimbridge" },
  { value: "bellevuefortdefrance", label: "Bellevue Fort-de-France" },
  { value: "francoisrabelais", label: "François Rabelais" },
  { value: "lyceedesada", label: "Lycée de Sada" },
  { value: "madamedestael", label: "Madame de Staël" },
  { value: "hectorberlioz", label: "Hector Berlioz" },
  { value: "gervillereache", label: "Gerville Réache" },
  { value: "madeleinemichelis", label: "Madeleine Michelis" },
  { value: "olympedegouges", label: "Olympe de Gouges" },
  { value: "jeanjacquesrousseau", label: "Jean-Jacques Rousseau" },
];